services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=agendamento_db'
      - 'POSTGRES_PASSWORD=teste123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d agendamento_db']
      interval: 5s
      timeout: 5s
      retries: 10
