spring.application.name=agendamento-api

# ---- Banco de dados (PostgreSQL / Neon) ----
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/agendamento_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:teste123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.docker.compose.enabled=false

server.port=8080
spring.profiles.active=dev
# para mudar para ambiente de testes só modificar para dev-test